# New Section

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
# classification
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix



In [2]:
df = pd.read_csv("/content/city_day.csv")
print(df.head())
print(df.tail())

        City      Date  PM2.5  PM10     NO    NO2    NOx  NH3     CO    SO2  \
0  Ahmedabad  1/1/2015    NaN   NaN   0.92  18.22  17.15  NaN   0.92  27.64   
1  Ahmedabad  1/2/2015    NaN   NaN   0.97  15.69  16.46  NaN   0.97  24.55   
2  Ahmedabad  1/3/2015    NaN   NaN  17.40  19.30  29.70  NaN  17.40  29.07   
3  Ahmedabad  1/4/2015    NaN   NaN   1.70  18.48  17.97  NaN   1.70  18.59   
4  Ahmedabad  1/5/2015    NaN   NaN  22.10  21.42  37.76  NaN  22.10  39.33   

       O3  Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14 AQI_Bucket  
0  133.36          NaN          NaN          NaN          NaN        NaN  
1   34.06          NaN          NaN          NaN          NaN        NaN  
2   30.70          NaN          NaN          NaN          NaN        NaN  
3   36.08          NaN          NaN          NaN          NaN        NaN  
4   39.31          NaN          NaN          NaN          NaN        NaN  
                City       Date  PM2.5   PM10    NO    NO2    NOx    NH3  \

In [17]:
# Clean column names first (important if any column names have leading/trailing spaces)
df.columns = df.columns.str.strip()

# Updated list – only numerical columns
cols_with_zeros = ['PM2.5', 'PM10', 'NO', 'NO2','NOx', 'NH3', 'CO', 'SO2']

# Replace 0 with NaN for these columns
df[cols_with_zeros] = df[cols_with_zeros].replace(0, np.nan)

# Fill NaNs with median of each column
df[cols_with_zeros] = df[cols_with_zeros].fillna(df[cols_with_zeros].median())
print(df.head())
print(df.tail())


        City      Date  PM2.5   PM10     NO    NO2    NOx    NH3     CO  \
0  Ahmedabad  1/1/2015  48.57  95.68   0.92  18.22  17.15  15.85   0.92   
1  Ahmedabad  1/2/2015  48.57  95.68   0.97  15.69  16.46  15.85   0.97   
2  Ahmedabad  1/3/2015  48.57  95.68  17.40  19.30  29.70  15.85  17.40   
3  Ahmedabad  1/4/2015  48.57  95.68   1.70  18.48  17.97  15.85   1.70   
4  Ahmedabad  1/5/2015  48.57  95.68  22.10  21.42  37.76  15.85  22.10   

     SO2      O3  Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  \
0  27.64  133.36          NaN          NaN          NaN          NaN   
1  24.55   34.06          NaN          NaN          NaN          NaN   
2  29.07   30.70          NaN          NaN          NaN          NaN   
3  18.59   36.08          NaN          NaN          NaN          NaN   
4  39.33   39.31          NaN          NaN          NaN          NaN   

  AQI_Bucket  
0        NaN  
1        NaN  
2        NaN  
3        NaN  
4        NaN  
                City      

In [18]:
df = df.dropna(subset=['AQI_Bucket'])


In [19]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['AQI_Bucket'] = le.fit_transform(df['AQI_Bucket'])


/tmp/ipython-input-19-2538893467.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['AQI_Bucket'] = le.fit_transform(df['AQI_Bucket'])


In [20]:
X = df[['PM2.5', 'PM10', 'NO', 'NO2','NOx', 'NH3', 'CO', 'SO2']]
y = df['AQI_Bucket']


In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)


In [21]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))



Accuracy: 0.703420523138833
Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.59      0.59       282
           1       0.73      0.74      0.73      1745
           2       0.53      0.53      0.53       555
           3       0.76      0.74      0.75      1655
           4       0.76      0.74      0.75       271
           5       0.66      0.70      0.68       462

    accuracy                           0.70      4970
   macro avg       0.67      0.67      0.67      4970
weighted avg       0.70      0.70      0.70      4970

Confusion Matrix:
 [[ 165    8    1  108    0    0]
 [   7 1287  167  266    2   16]
 [   1  151  293   10   10   90]
 [ 106  311   10 1225    0    3]
 [   0    2    8    3  201   57]
 [   0   14   72    1   50  325]]


In [22]:
# Random Forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.703420523138833
Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.59      0.59       282
           1       0.73      0.74      0.73      1745
           2       0.53      0.53      0.53       555
           3       0.76      0.74      0.75      1655
           4       0.76      0.74      0.75       271
           5       0.66      0.70      0.68       462

    accuracy                           0.70      4970
   macro avg       0.67      0.67      0.67      4970
weighted avg       0.70      0.70      0.70      4970

Confusion Matrix:
 [[ 165    8    1  108    0    0]
 [   7 1287  167  266    2   16]
 [   1  151  293   10   10   90]
 [ 106  311   10 1225    0    3]
 [   0    2    8    3  201   57]
 [   0   14   72    1   50  325]]


In [23]:

# SVM
svm = SVC()
svm.fit(X_train, y_train)

from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.703420523138833
Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.59      0.59       282
           1       0.73      0.74      0.73      1745
           2       0.53      0.53      0.53       555
           3       0.76      0.74      0.75      1655
           4       0.76      0.74      0.75       271
           5       0.66      0.70      0.68       462

    accuracy                           0.70      4970
   macro avg       0.67      0.67      0.67      4970
weighted avg       0.70      0.70      0.70      4970

Confusion Matrix:
 [[ 165    8    1  108    0    0]
 [   7 1287  167  266    2   16]
 [   1  151  293   10   10   90]
 [ 106  311   10 1225    0    3]
 [   0    2    8    3  201   57]
 [   0   14   72    1   50  325]]


In [24]:
# KNN
KNN = KNeighborsClassifier()
KNN.fit(X_train, y_train)


from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))



Accuracy: 0.703420523138833
Classification Report:
               precision    recall  f1-score   support

           0       0.59      0.59      0.59       282
           1       0.73      0.74      0.73      1745
           2       0.53      0.53      0.53       555
           3       0.76      0.74      0.75      1655
           4       0.76      0.74      0.75       271
           5       0.66      0.70      0.68       462

    accuracy                           0.70      4970
   macro avg       0.67      0.67      0.67      4970
weighted avg       0.70      0.70      0.70      4970

Confusion Matrix:
 [[ 165    8    1  108    0    0]
 [   7 1287  167  266    2   16]
 [   1  151  293   10   10   90]
 [ 106  311   10 1225    0    3]
 [   0    2    8    3  201   57]
 [   0   14   72    1   50  325]]


In [25]:
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Step 1: Scale your features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)  # X = your features like PM2.5, PM10, etc.

# Step 2: Train-test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

# Step 3: Use Logistic Regression with increased max_iter and alternate solver
logreg = LogisticRegression(max_iter=3000, solver='liblinear')  # 'liblinear' is good for small datasets
logreg.fit(X_train, y_train)

# Step 4: Evaluate
y_pred = logreg.predict(X_test)
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))


Accuracy: 0.6589537223340041
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       282
           1       0.59      0.83      0.69      1745
           2       0.29      0.01      0.01       555
           3       0.71      0.85      0.77      1655
           4       0.86      0.61      0.71       271
           5       0.73      0.55      0.63       462

    accuracy                           0.66      4970
   macro avg       0.53      0.47      0.47      4970
weighted avg       0.59      0.66      0.60      4970

Confusion Matrix:
 [[   0    4    0  278    0    0]
 [   0 1444    0  296    2    3]
 [   0  530    4    7    1   13]
 [   0  247    0 1406    0    2]
 [   0   31    0    0  166   74]
 [   0  172   10    0   25  255]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [27]:
# Create a DataFrame with X_test and predicted results
result_df = pd.DataFrame(X_test, columns=['PM2.5', 'PM10', 'NO', 'NO2','NOx', 'NH3', 'CO', 'SO2'])
result_df['Actual'] = y_test.values
result_df['Predicted'] = y_pred

# Save to CSV
result_df.to_csv('prediction_results.csv', index=False)


In [28]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
import joblib

# 1. Load the CSV file
df = pd.read_csv('city_day.csv')

# 2. Extract features and target
X = df[['PM2.5', 'PM10', 'NO', 'NO2', 'NH3', 'CO', 'SO2']]
y = df['AQI_Bucket']  # Make sure this is your label column

# 3. Train a model
model = DecisionTreeClassifier(random_state=42)
model.fit(X_train, y_train)

# 4. Save the model to a file
joblib.dump(model, 'ml_model.pkl')

print("Model trained and saved as ml_model.pkl")


Model trained and saved as ml_model.pkl
